baseURL = "https://sigita-sevceva.github.io/website"
languageCode = "en-us"
title = "Just Some Digital Humanities Research Projects"
publishDir = "docs"
theme = "ananke"

canonifyURLs = true

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 4 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = "https://www.facebook.com/killingsoftness"
  twitter = "https://twitter.com/soundsFierce"
  instagram = "https://www.instagram.com/soundsfierce/"
  youtube = ""
  github = "https://github.com/sigita-sevceva"
  gitlab = "https://gitlab.com/sigita-sevceva"
  linkedin = "https://www.linkedin.com/in/sigita-%C5%A1evceva-20149ba4/"
  mastodon = ""
  slack = ""
  stackoverflow = "https://stackoverflow.com/users/14243331/soundsfierce"
  rss = ""
  commentoEnable = false
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/pawel-czerwinski-tMbQpdguDVQ-unsplash.jpg"
  recent_posts_number = 3